### ISSUE TITLE
Proportionality: mandation

### ISSUE THREAD

**Issue by Hurstharrier** [best-practice-and-impact/aqua_book_revision#104]
From Phillipa R

"There shall always be an element of independence between the assurer and the analyst. The degree of separation depends on many factors including the importance of the output, and the size and complexity of the analysis. This does not mean that the analyst should not undertake assurance. It means that there should be some formal independent assurance." 

This doesn't seem consistent in mandation, we use both should and shall and also say that the analysts can undertake assurance.

**Comment by rebecca-wodcke-gad** [comment]
covered by issue #15
