### ISSUE TITLE
Quality assurance culture: Placement and focus

### ISSUE THREAD

**Issue by Hurstharrier** [best-practice-and-impact/aqua_book_revision#109]
From Phillipa R
Whilst obviously a big issue, given this is only for senior leaders, it feels a bit odd to have a section not everyone needs to read so early on. Wonder it this could be moved later on, or even as a separate doc? Not strong opinion though, or could maybe add some lines to say that it's useful for all analysts to be aware of the issues, even if they're not in charge of delivering against them

Best practice examples, work well when there is further detail elsewhere, like the DfE example, not sure the HMRC one says enough at the moment

**Comment by rebecca-wodcke-gad** [comment]
Added sentence to explain it is relevant to everyone, but leaving open as not changed examples
