### ISSUE TITLE
Definitions: Check that all terms are important in later chapters

### ISSUE THREAD

**Issue by irisoren-sg** [best-practice-and-impact/aqua_book_revision#11]
Ensure that the terms included are key in later chapters and referred to more than once. Else remove and define where they appear

- Change control
- Materiality

**Comment by irisoren-sg** [comment]
"materiality" only appears in 7.3. It will be defined in context and can be removed from Definitions chapter

**Comment by rebecca-wodcke-gad** [comment]
I've searched for each term 
Theses two don't appear at all:
**Materiality** - I'll remove
**Principles of analytical quality assurance** - should this move somewhere else? Includes RIGOUR box.

These three only appear once:
**Change control** - I'll remove and change the mention of this to change/version control
**Quality analysis** - propose leaving, although we don't refer to this term, it is an overarching theme
**Reproducible analytical pipelines** - I'll move this as a footnote to the design chapter

everything else appears at least twice.

@irisoren-sg which branch should branch off from to make these edits?

**Comment by irisoren-sg** [comment]
Thanks @rebecca-wodcke-gad I think it would be best to wait until we merge https://github.com/best-practice-and-impact/aqua_book_revision/pull/265. Alternatively, you can branch off https://github.com/best-practice-and-impact/aqua_book_revision/tree/258-creating-a-branch-for-all-of-the-editing-milestones, but we would still want to wait for the PR to be approved and merged

Re: 
* Principles of analytical quality assurance - should this move somewhere else? Includes RIGOUR box. Could this go in the introduction?
* Reproducible analytical pipelines - I'll move this as a footnote to the design chapter. There is already a call-out box in the design chapter

**Comment by Hurstharrier** [comment]
Happy with this.
