### ISSUE TITLE
Overview of the analytical lifecycle: Comment

### ISSUE THREAD

**Issue by Hurstharrier** [best-practice-and-impact/aqua_book_revision#110]
From Phillipa R

Whilst there is still a bit of content that isn't strictly related to quality, meaning duplication with the standard, I think the increased focus on quality has helped with the differentiation.

**Comment by rebecca-wodcke-gad** [comment]
@Hurstharrier are any changes needed here?

**Comment by Hurstharrier** [comment]
Nothing more required
