### ISSUE TITLE
Design: level of mandation

### ISSUE THREAD

**Issue by Hurstharrier** [best-practice-and-impact/aqua_book_revision#112]
From Phillipa R

7.2 Think 'should' is too strong a level given all of the different things listed, particularly for ad-hoc analysis, which the AB does cover.

**Comment by irisoren-sg** [comment]
List of "Should include" to be split into "should" and "for more complex analysis, may include"

**Comment by irisoren-sg** [comment]
Unclear what this refers to. Closing the issue as level of mandation has been checked and will be reviewed as a final checl
