### ISSUE TITLE
Definitions and key concepts: expand and clarify

### ISSUE THREAD

**Issue by Hurstharrier** [best-practice-and-impact/aqua_book_revision#123]
From Chris Payne
Roles and responsibilities felt a little difficult to find when it was located in the definitions and key concepts - might be better to have it's own section.

**Comment by rebecca-wodcke-gad** [comment]
@irisoren-sg @zarbspace @Hurstharrier was this discussed - do we want to move this section out of chapter 2?

**Comment by irisoren-sg** [comment]
@rebecca-wodcke-gad  We moved roles to Analytical Lifecycle chapter and changed the title of that chapter, and moved out of definitions #161

**Comment by rebecca-wodcke-gad** [comment]
@irisoren-sg ah yes, I see that now, thanks for closing off
