### ISSUE TITLE
Delivery and communication: new guidance from OSR ontransparency

### ISSUE THREAD

**Issue by Hurstharrier** [best-practice-and-impact/aqua_book_revision#124]
The OSR has recently published new guidance on transparency - it might be wise to reference this in section 9.3 [https://osr.statisticsauthority.gov.uk/publication/regulatory-guidance-on-intelligent-transparency/](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fosr.statisticsauthority.gov.uk%2Fpublication%2Fregulatory-guidance-on-intelligent-transparency%2F&data=05%7C02%7Calec.waterhouse%40energysecurity.gov.uk%7C172ca7fe22e441c08f2008dca0f59ce4%7Ccbac700502c143ebb497e6492d1b2dd8%7C0%7C0%7C638562223981916760%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=4aY6nKQCp6bXrdxMbA47bZyWeDGOtqy%2FIPQU7ZpUDic%3D&reserved=0)

**Comment by irisoren-sg** [comment]
Included in #74
