### ISSUE TITLE
Delivery and communication: reference to recommendations from PAC

### ISSUE THREAD

**Issue by Hurstharrier** [best-practice-and-impact/aqua_book_revision#125]
From Chris P

A recent PACAC report has recommended that the Analysis Function Standard guides analysts to publish any analysis that feeds into policy decision making. The wording in the AF Standard is currently quite high level and, if you consider the public as a key stakeholder, near enough makes this recommendation as it states: 

'Analysis should support decision-making by:  

Presenting the analysis in a way that is suitably presented for the intended audience, with findings, and the limitations and uncertainty around them, communicated clearly, objectively, and impartially to users and stakeholders '.

The Aquabook might want to ensure that it also promotes analysis being presented (and published where beneficial) for users but also stakeholders, whereby the public could be considered a key stakeholder in analysis that has been used to drive decision making.

**Comment by irisoren-sg** [comment]
Included in #74
