### ISSUE TITLE
Definitions: AI, ML and Black-box

### ISSUE THREAD

**Issue by irisoren-sg** [best-practice-and-impact/aqua_book_revision#138]
Add definitions for both AI and ML (and abbreviations) in definition section.

Hyperlink from each to pop-out box about black-box models stating that AI and ML are examples of black-box models. But other future types of BB models may arise

**Comment by irisoren-sg** [comment]
@rebecca-wodcke-gad FYI @Hurstharrier and I discussed this at our meeting. Alec will take this issue forward and ask you to review the PR

**Comment by rebecca-wodcke-gad** [comment]
Sounds good, thanks @irisoren-sg
