### ISSUE TITLE
Definitions/delivery: Documentation

### ISSUE THREAD

**Issue by irisoren-sg** [best-practice-and-impact/aqua_book_revision#14]
Should the documentation definitions be here, or in the delivery+communication section

**Comment by zarbspace** [comment]
18/07/2024 Decision: move documentation definitions to inset box in Chapter 9.

**Comment by rebecca-wodcke-gad** [comment]
move after PR #177 merged, which updates definitions

**Comment by rebecca-wodcke-gad** [comment]
@irisoren-sg PR #201 links to the documentation definitions, do we know longer want to move them to chapter 9?

**Comment by irisoren-sg** [comment]
@rebecca-wodcke-gad On writing it, I thought it worked okay with just linking to definitions. What do you think?

It also depends on how the documentation that is linked to other chapters is brought in
