### ISSUE TITLE
Introduction: Add visual showing what the QA process looks like

### ISSUE THREAD

**Issue by Hurstharrier** [best-practice-and-impact/aqua_book_revision#141]
From Matt Gurdon (GAD)
The intro section could usefully have a simple visual of what the QA process looks like, which could neatly provide links to associated sections and help inform how the “book” is laid out (section 5 does a bit of this but I think something slightly different would be beneficial for the intro)

**Comment by rebecca-wodcke-gad** [comment]
@irisoren-sg @zarbspace do you have any recommendations of tools to use to produce such a visual? I can ask around my team if not

**Comment by irisoren-sg** [comment]
@rebecca-wodcke-gad  I use inkscape or [draw.](https://www.drawio.com/) to make svg

Alternatively, https://mermaid.js.org/intro/ might be suitable and allow us to embed it as code directly into markdown

**Comment by Hurstharrier** [comment]
@rebecca-wodcke-gad  @zarbspace  @irisoren-sg  
I think figure 2 in chapter 5 would work if we put it into the introduction with hyperlinks.
