### ISSUE TITLE
Design, Analysis, Delivery and communication: add hyperlinks to resources mentioned in section 10 

### ISSUE THREAD

**Issue by Hurstharrier** [best-practice-and-impact/aqua_book_revision#144]
From Matt Gurden (GAD)
Would be good to have direct links through section 7, 8 and 9 to advice / tools for QA activity, eg some of the resources mentioned in section 10, as currently feels a little light in support for how to deliver appropriate QA

**Comment by rebecca-wodcke-gad** [comment]
@Hurstharrier is this now resolved through the more wholesale changes made to part 2?

**Comment by Hurstharrier** [comment]
Happy to close the issue
