### ISSUE TITLE
Proportionality and Definitions: Make statement on Degree of separation consistent

### ISSUE THREAD

**Issue by irisoren-sg** [best-practice-and-impact/aqua_book_revision#15]
In Definitions, Assurer and Analyst are said to be independent. In Proportionality, it says that there should be a degree of separation. We need to make this requirement consistent across chapters

**Comment by rebecca-wodcke-gad** [comment]
Similar to this point. in the 2nd paragraph of the 1st chapter, the 1st sentence says "shall" and the last sentence says "should". Perhaps replace this paragraph with:

The assurer and the analyst shall be independent. The degree of separation depends on many factors including the importance of the output, and the size and complexity of the analysis. This does not mean that the analyst should not undertake assurance, rather that there shall also be some formal independent assurance.

In definitions, replace must with shall

**Comment by rebecca-wodcke-gad** [comment]
Corrected in Proportionality-edits branch
