### ISSUE TITLE
Definitions:revisit definitions of verification and validation in principles of quality assurance

### ISSUE THREAD

**Issue by irisoren-sg** [best-practice-and-impact/aqua_book_revision#150]
Currently reads "**Verification and validation:** Analytical quality assurance is more than checking that the analysis is error-free and satisfies its specification (verification). It should also include checks that the analysis is appropriate, i.e. fit for the purpose for which it is being used (validation)."

Definition from wikipedia: 
Validation: Ensuring that the device meets the needs and requirements of its intended users and the intended use environment.
Verification: Ensuring that the device meets its specified design requirements

So should be swapped

**Comment by rebecca-wodcke-gad** [comment]
@irisoren-sg @zarbspace I disagree that these need swapping. Verification  - does it meet the spec, Validation - does the spec meet the needs of the users. That is what it already says and is consistent with the wikipedia definition?

**Comment by zarbspace** [comment]
I must admit, I got confused when I re-read them! If we're happy to leave as is, I'll close the pull request and delete the proposed change.
________________________________

**Comment by Hurstharrier** [comment]
@zarbspace @irisoren-sg  I agree with Iris and so we should close and drop the change

**Comment by irisoren-sg** [comment]
@zarbspace @rebecca-wodcke-gad @Hurstharrier  Since *we* are confused, I think we need a clearer statement :-)

**Comment by zarbspace** [comment]
Following our discussion, Iris and I decided that we need to revisit these definitions to check for sufficient clarity.

**Comment by rebecca-wodcke-gad** [comment]
It looks like these definitions have changed now so close this off? @zarbspace @irisoren-sg

**Comment by irisoren-sg** [comment]
@rebecca-wodcke-gad I don't know at what stage those definitions appeared. But @zarbspace and I agreed that the definitions as they stand need to be simplified to what you said in the comment above. So the issue is open. Do you want to change as above?

**Comment by rebecca-wodcke-gad** [comment]
@irisoren-sg done - I've made it much shorter, pretty much used the Wikipedia wording. I've added to PR #177
