### ISSUE TITLE
All Chapters: Part 2 - Remove Working with third parties

### ISSUE THREAD

**Issue by irisoren-sg** [best-practice-and-impact/aqua_book_revision#155]
See https://github.com/best-practice-and-impact/aqua_book_revision/discussions/156

**Comment by irisoren-sg** [comment]
@rebecca-wodcke-gad  #190 should not close this. In current part 2, there is a subheading in each chapter for working with third parties. So we need to remove this. Do you want to do it, or shall I assign it to myself as a separate issue an we unlink from #190 ?

**Comment by rebecca-wodcke-gad** [comment]
Ah good point, I'm happy to do this and add to the same PR
