### ISSUE TITLE
All chapters: fix hyperlinks between sections

### ISSUE THREAD

**Issue by irisoren-sg** [best-practice-and-impact/aqua_book_revision#176]
See https://github.com/best-practice-and-impact/aqua_book_revision/discussions/174

Once determined how to do this, search for hyperlinks to fix with "name =", then check where the tags are referred to

**Comment by irisoren-sg** [comment]
@Hurstharrier  @rebecca-wodcke-gad @zarbspace 

# To link to another [link text to appear](file.qmd)   NO SPACE BETWEEN PARENTHESES
# To link to a subsection in another chapter.
     - Get link by going to the relevant section in the rendered file, and right clicking. Copy the text "chapter.html#XXXXX"
     - Alternatively, use chapter.html#section_heading where section_heading is all lower case and spaces are replaced with "-"
     - Create link as [link text to appear](chapter.html#XXXXX) NO SPACE BETWEEN PARENTHESES
# To link to another URL: [link text to appear](URL) NO SPACE BETWEEN PARENTHESES

Shall we divvy it up as follows to check and insert hyperlinks:

1-3 Alec (on the assumption that there are fewer links in intro
4-5 Iris
6-7 Martin
8-9 Rebecca

Swapping the allocation so that we can review each other's sections at the same time.

@zarbspace  Will you have time to review? You seem to have a lot on ATM

**Comment by rebecca-wodcke-gad** [comment]
I've created a branch for this and fixed links in chapter 8. Will do chapter 9 on Monday

**Comment by irisoren-sg** [comment]
I've pushed the revised chapters 4-5

**Comment by Hurstharrier** [comment]
@irisoren-sg I have checked chaps 1-3 - no changes required

**Comment by rebecca-wodcke-gad** [comment]
Chapter 9 done and pushed
