### ISSUE TITLE
chapter name error: forEwOrd instead of forwArd

### ISSUE THREAD

**Issue by kateod-ukhsa** [best-practice-and-impact/aqua_book_revision#181]
ISSUE:
There is a spelling mistake in the name of one of the chapters. The chapter name/title is currently `forwArd` but it should be `forEwOrd`  instead. 

SOURCE: 
_The name of the section for comments made before the actual text (usually in a book) is **foreword**_ (see https://www.writersdigest.com/write-better-fiction/foreword-vs-forward-grammar-rules)

FILES AFFECTED
- `_quarto.yml`
- `README.md`
- ~`forward.qmd`~ -> `foreword.qmd`

**Comment by Hurstharrier** [comment]
Have changed to Foreword rather than forward on the main branch 
Thanks @kateod-ukhsa

**Comment by kateod-ukhsa** [comment]
@Hurstharrier The `forward.qmd` file still needs renaming ;)  https://github.com/best-practice-and-impact/aqua_book_revision/commit/4df227ba471b8bfe4593866e97706fb95a2e516d

**Comment by Hurstharrier** [comment]
@

**Comment by Hurstharrier** [comment]
@zarbspace  - martin any problem with renaming the file forward.qmd foreword.qmd? 
If not might you do this and close the issue again?

**Comment by Hurstharrier** [comment]
Noted and pending action


***@***.***

Alec Waterhouse [he/him] | Energy Statistics
Tel: 0300 068 2929 | 0778 994 7785 | ***@***.***
***@***.***%0b>

**Comment by zarbspace** [comment]
Updates completed as required.
