### ISSUE TITLE
All chapters: Check and replace wikipedia references

### ISSUE THREAD

**Issue by irisoren-sg** [best-practice-and-impact/aqua_book_revision#187]

**Comment by rebecca-wodcke-gad** [comment]
@Hurstharrier to take to wider group

**Comment by irisoren-sg** [comment]
@Hurstharrier to replace wikipedia entries

**Comment by Hurstharrier** [comment]
@irisoren-sg  @rebecca-wodcke-gad  @zarbspace - I have tried to find better references than the wikipedia ones. The trouble is they get very deep and specific. On reflection I think we ask those who object to wikipedia links to find us a better one!
