### ISSUE TITLE
Include impact of AI in all chapters where relevant

### ISSUE THREAD

**Issue by irisoren-sg** [best-practice-and-impact/aqua_book_revision#19]

**Comment by zarbspace** [comment]
Agreed that AI should be addressed appropriately in all chapters.

**Comment by rebecca-wodcke-gad** [comment]
@irisoren-sg has this been superseded by the new part 2 structure?

**Comment by irisoren-sg** [comment]
@rebecca-wodcke-gad Yes. Closing
