### ISSUE TITLE
Commissioner's responisbility: Should request information from the Analyst on accounting for uncertainty, and challenge them when it is absent, inadequate or ambiguous.

### ISSUE THREAD

**Issue by irisoren-sg** [best-practice-and-impact/aqua_book_revision#210]
This was in Engagement

"The commissioner:
Should request information from the Analyst on accounting for uncertainty, and challenge them when it is absent, inadequate or ambiguous."

Where should this be placed? 

Is it part of Delivery? Or is that too much of an after-thought?

**Comment by rebecca-wodcke-gad** [comment]
put into culture. Add section on uncertainty, everyone needs to be trained and should be part of ongoing conversations. Link to toolkits

**Comment by rebecca-wodcke-gad** [comment]
@irisoren-sg please find link to leadership uncertainty

**Comment by rebecca-wodcke-gad** [comment]
I'm not sure this does fit in culture after all. each part 2 chapter has a section on uncertainty so may just get rid of this? @irisoren-sg ?

**Comment by irisoren-sg** [comment]
@rebecca-wodcke-gad
Part 2 focuses on handling uncertainty in the analysis, rather than from the perspective of leadership and the wider culture. 

I have not read these resources closely yet, but can do so later this week and we can consider if it is better for Part 2 or QA culture

https://www.nao.org.uk/wp-content/uploads/2023/08/Good-practice-guide-Managing-uncertainty.pdf
