### ISSUE TITLE
All chapters: review mandation

### ISSUE THREAD

**Issue by irisoren-sg** [best-practice-and-impact/aqua_book_revision#214]
Check all mandation words are suitable and consistent across chapters, including

- [x] #103 
- [x] #99 
- [x] #97
- [ ] analysis.qmd - think it should read "The Analyst shall conduct the verification and validation activities"
- [ ] #27

**Comment by Hurstharrier** [comment]
I have checked and think the use fo shall etc is now correct.
~30 * shall
~120 should
~ 4 * may
~12 * might
~ 50 *can
