### ISSUE TITLE
Delivery: Add rereview of models to Delivery section

### ISSUE THREAD

**Issue by irisoren-sg** [best-practice-and-impact/aqua_book_revision#221]
> In some cases, models may be held in abeyance with a strong likelihood that they will be reused. In these cases, delivery and communication are not an end point. Regular reviews may be used to ensure they can be brought back into use when required by, for example, ensuring they are compatible with current software and hardware.

**Comment by irisoren-sg** [comment]
@rebecca-wodcke-gad 
I just realised that this issue relates to the changes the continuous review and maintenance edits that you added in #228 .

in #216 @Hurstharrier  and I discussed this separately, and thought that rather than in the lifecycle chapter, the text re: review would fit in Delivery chapter, as it discusses details rather than the "high-level" which is what is how the Analytical Lifecycle presents the stages. The text you added is great, but do you think it should stay in Analytical Lifecycle/Move to Delivery, or be included in both in some way?

**Comment by Hurstharrier** [comment]
@irisoren-sg  @rebecca-wodcke-gad  - I think regular review of the model is important for models using AI methods such as neural networks.

**Comment by rebecca-wodcke-gad** [comment]
@irisoren-sg the text I added covers the whole cycle rather than just delivery e.g. you may want to reconsider the scope or communication when re using. If you think all of it or some of the detail should move to the delivery section, I don't feel strongly about it

**Comment by rebecca-wodcke-gad** [comment]
Add to QA culture
does the model continue to be calibrated appropriately, this is particularly important for black box models?
Design
The process for reviewing inputs and calibrations should be planned in the design stage.
