### ISSUE TITLE
All chapters: AI assurance - Find external contacts

### ISSUE THREAD

**Issue by irisoren-sg** [best-practice-and-impact/aqua_book_revision#242]

**Comment by irisoren-sg** [comment]
But as a back-up, these are the co-authors of the [ValidateAI position paper](https://img1.wsimg.com/blobby/go/2cca2b20-026f-497e-89e3-022a5f0de15b/downloads/120424%20Validate%20AI%20Position%20Statement%20DH.pdf?ver=1725723173228)

Dr A. Bellotti, School of Computer Science, University of Nottingham, Ningbo 
Dr Zeynep Engin, Data for Policy CIC
Professor D.J. Hand, Department of Mathematics, Imperial College, London 
Seb Hargreaves, The Operational Research Society
Gile Herdale, Herdale Digital Consulting 
Ed Humpherson, Office for Statistical Regulation 
Dr Mark Kennedy, Data Science Institute, Imperial College, London 
Shakeel Khan, Validate AI CIC
Professor Marta Kwiatkowska, The University of Oxford 
Gilbert Owusu, Director of Data & AI at BT

**Comment by Hurstharrier** [comment]
Have got Turing Centre involved
