### ISSUE TITLE
Resources: Include Tools and main references

### ISSUE THREAD

**Issue by irisoren-sg** [best-practice-and-impact/aqua_book_revision#263]
Identify the important issues

**Comment by irisoren-sg** [comment]
@Hurstharrier to write to wider group

**Comment by rebecca-wodcke-gad** [comment]
[Aqua book reference comparison tables.xlsx](https://github.com/user-attachments/files/17746117/Aqua.book.reference.comparison.tables.xlsx)

**Comment by rebecca-wodcke-gad** [comment]
repeat
