### ISSUE TITLE
All chapters: use of shall / should etc. aligns with the terms used in the Functional Standard for Analysis

### ISSUE THREAD

**Issue by zarbspace** [best-practice-and-impact/aqua_book_revision#27]
Need to ensure that anything we define as shall/should/etc. aligns with the term used in the Analytical Standard. We don't want to put anything at a different level in the Aqua book compared with the standard.

**Comment by rebecca-wodcke-gad** [comment]
From Phillipa R

Seems to be more shalls than I would have expected, should may be more appropriate as this gives the option to comply or explain. There are also references to other terms like "needs to be" "must", which should use standards terms
