### ISSUE TITLE
Introduction: Link between "Assurance is required for audit purposes" and link to Managing Public Money reference

### ISSUE THREAD

**Issue by zarbspace** [best-practice-and-impact/aqua_book_revision#33]
Is this the right reference?

**Comment by zarbspace** [comment]
Check with Ian on source

**Comment by rebecca-wodcke-gad** [comment]
We now link to this resource later in the book (culture chapter) so maybe just remove this link?

**Comment by Hurstharrier** [comment]
This is the

**Comment by Hurstharrier** [comment]
This is the correct reference and there is more on this in the rest of the book.
