### ISSUE TITLE
Delivery: BCM register and addendum and remove PLACEHOLDER

### ISSUE THREAD

**Issue by irisoren-sg** [best-practice-and-impact/aqua_book_revision#54]
### Discussed in https://github.com/best-practice-and-impact/aqua_book_revision/discussions/29

<div type='discussions-op-text'>

<sup>Originally posted by **irisoren-sg** June 25, 2024</sup>
People have asked me how the Aqua book addendum relates to the contents in the new Aqua book, and whether the BCM register is going to be extended to Business Critical Analysis.

At the moment, the addendum is not referred to. Do we need to link to it, or are we going to move the material from the Addendum to the main book?

And is the register still going to be only recommended for models, or all analysis?</div>

If a Sign-off chapter is being added, then this should go there rather than delivery

**Comment by rebecca-wodcke-gad** [comment]
@irisoren-sg is this covered by section 9.9?
