### ISSUE TITLE
Bibliography: Complete the bibliography and link to citations in text

### ISSUE THREAD

**Issue by zarbspace** [best-practice-and-impact/aqua_book_revision#6]
bibliography.bib needs to be fully populated and linked to references.

**Comment by rebecca-wodcke-gad** [comment]
I'm not certain of the difference between the References vs the Additional resources?

**Comment by zarbspace** [comment]
Decision to delete references section.

**Comment by rebecca-wodcke-gad** [comment]
[Aqua book reference comparison tables_after combining additional resource.xlsx](https://github.com/user-attachments/files/17748237/Aqua.book.reference.comparison.tables_after.combining.additional.resource.xlsx)
