### ISSUE TITLE
Delivery: Change to "Delivery, Communication and Sign-Off"

### ISSUE THREAD

**Issue by irisoren-sg** [best-practice-and-impact/aqua_book_revision#61]
Sign-off appears in the analytical life-cycle, but does not have a chapter. It seems to me that adding to model register should come at the sign-off stage rather than delivery&communication.

If so, we can remove much of the contents of 5.1.5 and include it in the sign-off chapter as we have done for other phases

**Comment by rebecca-wodcke-gad** [comment]
reopening as partly covered by PR

**Comment by rebecca-wodcke-gad** [comment]
now updated in analytical lifecycle chapter so re-closing
