### ISSUE TITLE
All chapters: Part 2 Structure

### ISSUE THREAD

**Issue by irisoren-sg** [best-practice-and-impact/aqua_book_revision#67]
Chapter 7 has structure:
- Intro & Summary
    - Responsibility by role
- Design
- Testing (i.e. assurance activities)
- Documentation
- Uncertainty
- RAP 
- AI/ML

Most of these subsections could be used for the other part 2 chapters

Do we want to adhere to a general structure

- Intro & Summary
    - Responsibility by role
- Assurance activities
- Documentation
- Uncertainty
- AI/ML
- Multi-use models
- Other sections that are relevant to the chapter

Relates to #58

**Comment by irisoren-sg** [comment]
Go with structure proposed above

**Comment by irisoren-sg** [comment]
- Intro & Summary
- Responsibility by role
- Assurance activities
- Documentation
- Uncertainty
- AI/ML
- Multi-use models
- Working with third parties
- Other sections that are relevant to the chapter

**Comment by rebecca-wodcke-gad** [comment]
@irisoren-sg is this now superseded by other issues so can be closed?

**Comment by irisoren-sg** [comment]
@rebecca-wodcke-gad Not yet. I want to make sure that the phrasing used for the subtitles is consistent across chapters. I will work on this on Wednesday and submit a PR to close
