### ISSUE TITLE
Delivery: Edits

### ISSUE THREAD

**Issue by irisoren-sg** [best-practice-and-impact/aqua_book_revision#74]
- [x] "This chapter gives the Analyst, the Commissioner of analysis and other interested groups advice and information on how best to advise on the assurance and communicate analysis." -> "This chapter provides information on the processes around assurance of communication of analysis and delivery of analytical outputs"
- [x] Add responsibilities by role. Include Assurer responsibility removed from Analysis section: The assurer shall also confirm the work has been appropriately scoped, executed, validated, and verified and documented to the approver. 
- [x] "That the analysis has undergone appropriate analytical governance (sign offs);"  if sign off is the final stage, should this be part of the preceding delivery stage?
- [x] "Where applicable the code of practice for publications has been followed." - add hyperlinks
- [x] Much of what is in delivery is part of the Sign-off in 5.1.5. Need to decide how we delineate these stages
- [x] Multi-use model delivery considerations
- [x] AI/ML delivery considerations
- [x] Communication - emphasise  "Assurance of communication" - i.e. that the Analyst and Assurer have the joint responsibilities to adhere to the communication requirements specified
- [x] Fix shall/should/must in section: ""The analyst must comply with the code of practice when they publish official statistics. Some examples are given below...""
- [x] #51 
- [x] #53
- [x] #54 and #114
- [x] #57 
- [x] #124
- [x] #125 
- [ ] Add assurer responsibility from Analysis section: The Approver scrutinises the work of the analyst and assurer and shall be confident that the analysis:
* Meets its design requirements;
* Is of sufficient quality and
* Is adequately documented.

**Comment by rebecca-wodcke-gad** [comment]
reopening to check non-ticked items
