### ISSUE TITLE
All Chapters: AFTER EDITS COMPLETED Links to other sections 

### ISSUE THREAD

**Issue by Hurstharrier** [best-practice-and-impact/aqua_book_revision#80]
Should the following bullets in the introduction link to the parts of the book that address it

- working with third parties such as contractors and academic groups and,
- publishing models

**Comment by irisoren-sg** [comment]
And check for other necessary links

**Comment by irisoren-sg** [comment]
TO DO AFTER EDITS COMPLETED

**Comment by irisoren-sg** [comment]
ALso #84
