### ISSUE TITLE
Clarify "There shall always be an element of independence between the assurer and the analyst."

### ISSUE THREAD

**Issue by Hurstharrier** [best-practice-and-impact/aqua_book_revision#87]
This sentence leaves a lot of "wiggle room" suggest

"Assurance shall be carried out by independent assurers. The degree of separation between the analyst and the assurer should take in to consideration factors such as materiality of the output, and the size and complexity of the analysis."

**Comment by rebecca-wodcke-gad** [comment]
Overlaps with another issue, can we close off @Hurstharrier?

**Comment by Hurstharrier** [comment]
happy to close
