### ISSUE TITLE
Quality Assurance Culture: Clarify "Analysis should be peer reviewed by independent individuals or groups, who are independent of operational "

### ISSUE THREAD

**Issue by Hurstharrier** [best-practice-and-impact/aqua_book_revision#89]
Use the words in the proportionality section e.g.

Analysis should be validated and verified by independent assurer(s).

**Comment by rebecca-wodcke-gad** [comment]
changed this in issue #79, can we now close @Hurstharrier ?

**Comment by Hurstharrier** [comment]
@rebecca-wodcke-gad  - happy to close

**Comment by Hurstharrier** [comment]
@rebecca-wodcke-gad noted this is changed in issue #79
