### ISSUE TITLE
Quality assurance culture: Need a link to the source document for

### ISSUE THREAD

**Issue by Hurstharrier** [best-practice-and-impact/aqua_book_revision#93]
For Arm’s Length Bodies (ALBs) the Accounting Officer is accountable for ensuring the requirements set out in the AQuA Book are met

**Comment by rebecca-wodcke-gad** [comment]
@Hurstharrier not sure what is needed here

**Comment by Hurstharrier** [comment]
@rebecca-wodcke-gad sorry for taking so long to follow this up.  Apologies this is a long thread

There are two things here.

**Managing Public Money - NAO and HMT guidance**
There is a document (NAO approved) called "Managing Public Money" https://www.gov.uk/government/publications/managing-public-money . 
This sets out in Annex 4.1 that the "Supported by the board, the accounting officer of a central government organisation should oversee the use and quality assurance (QA) of models within the organisation. There should be sufficient feedback for the accounting officer to be able to track progress and adjust the process."  In practice this accountability is usually delegated to a senior manager in the organisation usually the head of analysis. 

So I think the paragraph 4.1 should refer to this. Something like
Governance supports a strong quality assurance culture, by overseeing the management and assurance of analysis.  Managing Public Money Annex 4.2 states "the accounting officer of a central government organisation should oversee the use and quality assurance (QA) of models within the organisation"  (https://www.gov.uk/government/publications/managing-public-money) . In practice this responsibility is usually assigned to a senior manager such as the head of analysis. The [Analysis Function Standard] (https://www.gov.uk/government/publications/government-analysis-functional-standard–2) sets out in more detail the requirements for a governance framework for analysis. Each organisation should have a defined and established approach to assurance, which should be applied proportionately to the risk and value of the activity and integrated with the organisation’s overall assurance framework. 

On ALBs - the **managing public money applies** but it it gets a bit complicated.  Normally the AO of the ALB commits in a "framework" document to applying MPM and the Functional Standards and providing a report to the Principle Accounting Officer that this is the case. 

So I think we should say something about this like 
"This guidance also applies to Arms Length Bodies. They may set out in a framework document how their Accounting Officer will demonstrate compliance with Managing Public Money. "

I could create a branch to address this - what do you think?
