### ISSUE TITLE
Engagement: Approvers roles

### ISSUE THREAD

**Issue by Hurstharrier** [best-practice-and-impact/aqua_book_revision#96]
[https://best-practice-and-impact.github.io/aqua_book_revision/engagement_and_scoping.html#the-approvers-responsibilities-during-engagement-and-scoping](url)

Should the approver have any documentation tasks ?

I think their role is something like "shall ensure that sufficiently qualified and experienced assurers are assigned" 

Should there also be something about making sure the assurers have enough time to do the assurance?

**Comment by irisoren-sg** [comment]
The approver might provide support in providing a sufficiently qualified and experienced assurer
