### ISSUE TITLE
Design: Clarify commissioners role - level of mandation

### ISSUE THREAD

**Issue by Hurstharrier** [best-practice-and-impact/aqua_book_revision#97]
[https://best-practice-and-impact.github.io/aqua_book_revision/design.html#the-commissioners-responsibilities-during-design](url)

Think this ought to be phrased a can or may

The Commissioner _may_ review the plan. They should agree with the Analyst that their approach will satisfy their requirements.

**Comment by irisoren-sg** [comment]
Check in PR for Design edits
