### ISSUE TITLE
Clarifying meaning of "dry run"

### ISSUE THREAD

**Issue by Hurstharrier** [best-practice-and-impact/aqua_book_revision#98]
[Best practice is to dry run with independent assurance of the proposed approach to see if the plan:](url)

Should this be rephrased  as follows?

Testing assurance methods before they are put into practice can be used to provide an indication that the proposed approach will:

Delivers as intended
Adequately addresses the complexities of the customer issue for this purpose
Is well-structured for the purpose, data driven, and reflects a robust overall design.

The assurer and the analyst can collaborate on the design and testing of assurance approaches.

**Comment by irisoren-sg** [comment]
Text has been removed. Do we want to include this somewhere?

**Comment by Hurstharrier** [comment]
@irisoren-sg  
This is covered in the section 8.3.1 without mentioning the words "dry run" 

"Dynamic analysis: tests the behaviour of the system or code to find errors that arise during execution. " 

Do you think that would read better if we referred a model as well as a system - not sure adding the words dry run adds much. It would then read

"Dynamic analysis: tests the behaviour of the system, model or code to find errors that arise during execution. "
